<?php
$value = array (
  'wwwprefix' => 'http://www.yangyutuan.cn',
  'imgprefix' => 'http://www.yangyutuan.cn',
  'cssprefix' => 'http://www.yangyutuan.cn',
  'sitename' => '洋芋团',
  'sitetitle' => '洋芋团，团就对了',
  'abbreviation' => '洋芋团',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'editor' => 'kind',
  'indexteam' => '0',
  'sideteam' => '0',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'kefu_hotline' => '020-123456',
  'server_time' => '9:00-18:00',
  'tousu_email' => '4545565@bn.com',
  'givecredit' => '10',
);
?>